[versions]
agp = "8.7.1"
core = "1.10.0"

[libraries]
core = { group = "androidx.core", name = "core", version.ref = "core" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

